"""
In-memory domain models and seeded data representing Northeast India's
8 states: Assam, Arunachal Pradesh, Meghalaya, Manipur, Mizoram, Nagaland, Tripura, Sikkim.
"""

from typing import List, Dict, Any
from datetime import datetime

# Pre-seeded Risk Zones in Northeast India
RISK_ZONES: List[Dict[str, Any]] = [
    {
        "id": "RZ-SK-01",
        "name": "Singtam - Rangpo Highway Corridor",
        "district": "Pakyong",
        "state": "Sikkim",
        "latitude": 27.2345,
        "longitude": 88.5123,
        "riskScore": 88,
        "riskLevel": "CRITICAL",
        "rainfall24h": 142.5,
        "rainfall7d": 412.0,
        "soilMoisture": 91.2,
        "slope": 48.0,
        "elevation": 720.0,
        "historicalLandslides": 19,
        "populationExposed": 14200,
        "status": "Evacuation Warning Active",
        "criticalInfrastructure": ["NH-10 Lifeline", "Singtam Power Substation", "Rangpo Checkpost Bridge"],
        "sensorsActive": 8,
        "lastUpdated": datetime.utcnow().isoformat() + "Z"
    },
    {
        "id": "RZ-ML-01",
        "name": "Cherrapunji - Sohra Escarpment Slope",
        "district": "East Khasi Hills",
        "state": "Meghalaya",
        "latitude": 25.2702,
        "longitude": 91.7323,
        "riskScore": 79,
        "riskLevel": "HIGH",
        "rainfall24h": 188.0,
        "rainfall7d": 560.0,
        "soilMoisture": 88.4,
        "slope": 52.0,
        "elevation": 1430.0,
        "historicalLandslides": 24,
        "populationExposed": 8900,
        "status": "High Alert Triggered",
        "criticalInfrastructure": ["SH-5 Cherra Route", "Sohra Water Distribution Canal"],
        "sensorsActive": 6,
        "lastUpdated": datetime.utcnow().isoformat() + "Z"
    },
    {
        "id": "RZ-AR-01",
        "name": "Bhalukpong - Tenga Sela Pass Axis",
        "district": "West Kameng",
        "state": "Arunachal Pradesh",
        "latitude": 27.0125,
        "longitude": 92.6450,
        "riskScore": 84,
        "riskLevel": "CRITICAL",
        "rainfall24h": 128.0,
        "rainfall7d": 380.5,
        "soilMoisture": 86.0,
        "slope": 55.0,
        "elevation": 2150.0,
        "historicalLandslides": 16,
        "populationExposed": 5400,
        "status": "BRO Convoy Movement Halted",
        "criticalInfrastructure": ["Strategic Defense Highway", "Tenga Valley Outpost Bridge"],
        "sensorsActive": 5,
        "lastUpdated": datetime.utcnow().isoformat() + "Z"
    },
    {
        "id": "RZ-AS-01",
        "name": "Haflong - Dima Hasao Hill Slopes",
        "district": "Dima Hasao",
        "state": "Assam",
        "latitude": 25.1764,
        "longitude": 93.0234,
        "riskScore": 74,
        "riskLevel": "HIGH",
        "rainfall24h": 98.4,
        "rainfall7d": 290.0,
        "soilMoisture": 82.5,
        "slope": 38.0,
        "elevation": 680.0,
        "historicalLandslides": 12,
        "populationExposed": 16500,
        "status": "Railway Cutting Inspection Underway",
        "criticalInfrastructure": ["Lumding-Badarpur Hill Railway Line", "NH-54E Haflong By-pass"],
        "sensorsActive": 4,
        "lastUpdated": datetime.utcnow().isoformat() + "Z"
    },
    {
        "id": "RZ-MN-01",
        "name": "Tupul - Noney Railway Tunnel Zone",
        "district": "Noney",
        "state": "Manipur",
        "latitude": 24.7890,
        "longitude": 93.6540,
        "riskScore": 91,
        "riskLevel": "CRITICAL",
        "rainfall24h": 156.0,
        "rainfall7d": 475.0,
        "soilMoisture": 94.8,
        "slope": 58.0,
        "elevation": 890.0,
        "historicalLandslides": 28,
        "populationExposed": 4100,
        "status": "Critical Siphon Pumping Deployed",
        "criticalInfrastructure": ["Jiribam-Imphal Railway Project Yard", "Ijei River Damming Risk Point"],
        "sensorsActive": 10,
        "lastUpdated": datetime.utcnow().isoformat() + "Z"
    },
    {
        "id": "RZ-MZ-01",
        "name": "Aizawl Bawngkawn - Ramhlun Ridge",
        "district": "Aizawl",
        "state": "Mizoram",
        "latitude": 23.7420,
        "longitude": 92.7230,
        "riskScore": 68,
        "riskLevel": "HIGH",
        "rainfall24h": 82.0,
        "rainfall7d": 240.0,
        "soilMoisture": 77.0,
        "slope": 44.0,
        "elevation": 1132.0,
        "historicalLandslides": 11,
        "populationExposed": 22000,
        "status": "Urban Slope Retaining Wall Monitored",
        "criticalInfrastructure": ["Aizawl Urban Arterial Road", "Ramhlun Gravity Water Tank"],
        "sensorsActive": 7,
        "lastUpdated": datetime.utcnow().isoformat() + "Z"
    },
    {
        "id": "RZ-NL-01",
        "name": "Kohima - Phesama Sinking Zone",
        "district": "Kohima",
        "state": "Nagaland",
        "latitude": 25.6420,
        "longitude": 94.1120,
        "riskScore": 63,
        "riskLevel": "HIGH",
        "rainfall24h": 76.5,
        "rainfall7d": 210.0,
        "soilMoisture": 74.0,
        "slope": 36.0,
        "elevation": 1444.0,
        "historicalLandslides": 14,
        "populationExposed": 18500,
        "status": "Creep Sensor Warning Active",
        "criticalInfrastructure": ["NH-2 Kohima-Imphal Highway", "Phesama Electric Grid Line"],
        "sensorsActive": 5,
        "lastUpdated": datetime.utcnow().isoformat() + "Z"
    },
    {
        "id": "RZ-TR-01",
        "name": "Jampui Hills Orange Ridge",
        "district": "North Tripura",
        "state": "Tripura",
        "latitude": 23.9540,
        "longitude": 92.2780,
        "riskScore": 28,
        "riskLevel": "LOW",
        "rainfall24h": 22.0,
        "rainfall7d": 65.0,
        "soilMoisture": 42.0,
        "slope": 22.0,
        "elevation": 930.0,
        "historicalLandslides": 2,
        "populationExposed": 3200,
        "status": "Normal Green Condition",
        "criticalInfrastructure": ["Vanghmun Rural Road"],
        "sensorsActive": 2,
        "lastUpdated": datetime.utcnow().isoformat() + "Z"
    }
]

# Historical & Recent Incident Records
INCIDENTS: List[Dict[str, Any]] = [
    {
        "id": "INC-2024-001",
        "title": "Massive Mudflow & Rockfall at NH-10 29th Mile",
        "district": "Pakyong",
        "state": "Sikkim",
        "latitude": 27.2105,
        "longitude": 88.5020,
        "severity": "CRITICAL",
        "status": "Active Rescue / Road Clearance",
        "timestamp": "2024-08-14T06:30:00Z",
        "rainfallAtEvent": 168.4,
        "casualties": 0,
        "roadBlocked": True,
        "description": "Heavy overnight cloudburst triggered 80-meter debris slide blocking NH-10, disconnecting Gangtok from Siliguri.",
        "teamsDispatched": ["NDRF 2nd Battalion", "Border Roads Organisation (GREF)", "SDRF Gangtok"]
    },
    {
        "id": "INC-2024-002",
        "title": "Slope Failure on Haflong Railway Escarpment",
        "district": "Dima Hasao",
        "state": "Assam",
        "latitude": 25.1820,
        "longitude": 93.0110,
        "severity": "HIGH",
        "status": "Track Stabilized / Restricting Speed",
        "timestamp": "2024-07-28T14:15:00Z",
        "rainfallAtEvent": 112.0,
        "casualties": 0,
        "roadBlocked": False,
        "description": "Earth slip deposited mud on ballast track. NF Railway deployed geo-textile reinforcement.",
        "teamsDispatched": ["Northeast Frontier Railway Engineering Wing", "Assam Disaster Management Quick Team"]
    },
    {
        "id": "INC-2024-003",
        "title": "Road Subsidence on NH-29 Chumukedima-Kohima",
        "district": "Chumukedima",
        "state": "Nagaland",
        "latitude": 25.7600,
        "longitude": 93.8200,
        "severity": "HIGH",
        "status": "Single Lane Diverted",
        "timestamp": "2024-08-02T19:45:00Z",
        "rainfallAtEvent": 89.2,
        "casualties": 0,
        "roadBlocked": True,
        "description": "Pore pressure build-up resulted in 20m shoulder collapse along old four-lane cutting.",
        "teamsDispatched": ["Nagaland PWD Highway", "Traffic Police Emergency Unit"]
    }
]

# Active Disaster Alerts & Bulletins
ALERTS: List[Dict[str, Any]] = [
    {
        "id": "ALT-2024-RED-089",
        "title": "RED WARNING: Imminent Landslide Trigger Probability > 85%",
        "level": "RED",
        "category": "Immediate Evacuation Alert",
        "district": "Pakyong & Mangan",
        "state": "Sikkim",
        "message": "Continuous 24h rainfall has exceeded 140mm critical threshold on already saturated metamorphic rock slopes. Debris flows imminent along NH-10 corridor.",
        "actionRequired": "Evacuate high-slope habitations within 500m of drainage channels to designated shelter centers. Halt all vehicular transit on NH-10.",
        "issuedAt": "2024-09-05T04:00:00Z",
        "validUntil": "2024-09-06T18:00:00Z",
        "bulletinNumber": "GSI-NER-EW-2024-0982",
        "affectedPopulation": 18500
    },
    {
        "id": "ALT-2024-ORANGE-054",
        "title": "ORANGE ALERT: Slope Creep Acceleration in Southern Slopes",
        "level": "ORANGE",
        "category": "Precautionary Standby",
        "district": "East Khasi Hills",
        "state": "Meghalaya",
        "message": "Sohra-Shella road sector showing 4.2mm/hr displacement on borehole inclinometers with heavy rain forecast.",
        "actionRequired": "Restrict heavy goods carriers. Place earthmoving machinery on standby at km 32 and km 47.",
        "issuedAt": "2024-09-05T06:30:00Z",
        "validUntil": "2024-09-06T12:00:00Z",
        "bulletinNumber": "GSI-NER-EW-2024-0983",
        "affectedPopulation": 9200
    },
    {
        "id": "ALT-2024-YELLOW-031",
        "title": "YELLOW ADVISORY: Elevated Soil Moisture on Highway Slopes",
        "level": "YELLOW",
        "category": "Vigilance Advisory",
        "district": "Kohima",
        "state": "Nagaland",
        "message": "Persistent light to moderate showers keeping shear strength low on Phesama-Dzülake slopes.",
        "actionRequired": "Night driving discouraged on bypass corridors. Village disaster committees to inspect drainage ditches.",
        "issuedAt": "2024-09-05T08:00:00Z",
        "validUntil": "2024-09-07T00:00:00Z",
        "bulletinNumber": "GSI-NER-EW-2024-0984",
        "affectedPopulation": 14000
    }
]

# Weather Stations & Observations in NER
WEATHER_DATA: List[Dict[str, Any]] = [
    {
        "district": "Pakyong",
        "state": "Sikkim",
        "temperature": 18.5,
        "humidity": 96,
        "rainfallCurrent": 14.2,
        "rainfall24h": 142.5,
        "rainfallForecast24h": 110.0,
        "windSpeed": 18.5,
        "condition": "Heavy Monsoonal Rain",
        "cloudCover": 100,
        "lastObservation": datetime.utcnow().isoformat() + "Z"
    },
    {
        "district": "East Khasi Hills",
        "state": "Meghalaya",
        "temperature": 19.0,
        "humidity": 98,
        "rainfallCurrent": 22.0,
        "rainfall24h": 188.0,
        "rainfallForecast24h": 145.0,
        "windSpeed": 22.0,
        "condition": "Torrential Downpour",
        "cloudCover": 100,
        "lastObservation": datetime.utcnow().isoformat() + "Z"
    },
    {
        "district": "West Kameng",
        "state": "Arunachal Pradesh",
        "temperature": 14.2,
        "humidity": 92,
        "rainfallCurrent": 9.5,
        "rainfall24h": 128.0,
        "rainfallForecast24h": 85.0,
        "windSpeed": 12.0,
        "condition": "Cloudy with Gusts & Showers",
        "cloudCover": 95,
        "lastObservation": datetime.utcnow().isoformat() + "Z"
    },
    {
        "district": "Dima Hasao",
        "state": "Assam",
        "temperature": 24.8,
        "humidity": 89,
        "rainfallCurrent": 8.0,
        "rainfall24h": 98.4,
        "rainfallForecast24h": 60.0,
        "windSpeed": 15.0,
        "condition": "Intermittent Moderate Rains",
        "cloudCover": 90,
        "lastObservation": datetime.utcnow().isoformat() + "Z"
    },
    {
        "district": "Noney",
        "state": "Manipur",
        "temperature": 22.1,
        "humidity": 94,
        "rainfallCurrent": 18.0,
        "rainfall24h": 156.0,
        "rainfallForecast24h": 120.0,
        "windSpeed": 14.0,
        "condition": "Squally Heavy Showers",
        "cloudCover": 100,
        "lastObservation": datetime.utcnow().isoformat() + "Z"
    },
    {
        "district": "Aizawl",
        "state": "Mizoram",
        "temperature": 21.5,
        "humidity": 86,
        "rainfallCurrent": 6.5,
        "rainfall24h": 82.0,
        "rainfallForecast24h": 50.0,
        "windSpeed": 11.0,
        "condition": "Drizzle & Foggy Ridge",
        "cloudCover": 85,
        "lastObservation": datetime.utcnow().isoformat() + "Z"
    },
    {
        "district": "Kohima",
        "state": "Nagaland",
        "temperature": 20.0,
        "humidity": 88,
        "rainfallCurrent": 5.0,
        "rainfall24h": 76.5,
        "rainfallForecast24h": 45.0,
        "windSpeed": 10.0,
        "condition": "Overcast with Light Rain",
        "cloudCover": 90,
        "lastObservation": datetime.utcnow().isoformat() + "Z"
    },
    {
        "district": "North Tripura",
        "state": "Tripura",
        "temperature": 28.0,
        "humidity": 72,
        "rainfallCurrent": 0.0,
        "rainfall24h": 22.0,
        "rainfallForecast24h": 15.0,
        "windSpeed": 8.0,
        "condition": "Partly Cloudy",
        "cloudCover": 45,
        "lastObservation": datetime.utcnow().isoformat() + "Z"
    }
]

# Field Reports (mutable in memory)
FIELD_REPORTS: List[Dict[str, Any]] = [
    {
        "id": "REP-2024-001",
        "reporterName": "Tashi Bhutia",
        "reporterPhone": "+91 98451 22341",
        "role": "Village Disaster Volunteer",
        "district": "Pakyong",
        "state": "Sikkim",
        "locationName": "Singtam Lower Bazaar Hillside",
        "latitude": 27.2380,
        "longitude": 88.5140,
        "hazardType": "Tension Cracks on Road Surface",
        "urgencyLevel": "URGENT",
        "description": "Noticed 3-inch wide tension cracks opening along the retaining wall above the lower market road after morning downpour.",
        "roadBlocked": False,
        "structuresAtRisk": 4,
        "photoUrl": "https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?w=600",
        "id": "REP-2024-001",
        "timestamp": "2024-09-05T07:15:00Z",
        "verificationStatus": "VERIFIED_BY_ENGINEER",
        "aiRiskScore": 86
    }
]
