import { SensorData, SensorHistoryPoint } from './types';

function generateInitialHistory(baseVal: number, batteryBase: number, signalBase: number): SensorHistoryPoint[] {
  const points: SensorHistoryPoint[] = [];
  const now = Date.now();
  for (let i = 10; i >= 0; i--) {
    const time = new Date(now - i * 3 * 60 * 1000);
    const noise = (Math.random() - 0.5) * (baseVal * 0.05);
    points.push({
      timestamp: `${String(time.getHours()).padStart(2, '0')}:${String(time.getMinutes()).padStart(2, '0')}`,
      value: Number((baseVal + noise).toFixed(2)),
      battery: Math.min(100, Math.max(10, Math.round(batteryBase - i * 0.1))),
      signalStrength: Math.min(100, Math.max(20, Math.round(signalBase + (Math.random() - 0.5) * 4)))
    });
  }
  return points;
}

export const INITIAL_NER_SENSORS: SensorData[] = [
  // 1. Sikkim - Pakyong (Singtam NH-10 Corridor)
  {
    sensorId: 'SEN-SK-SM-01',
    district: 'Pakyong',
    state: 'Sikkim',
    location: 'Singtam 29th Mile Retaining Wall (Upper Tier)',
    latitude: 27.2345,
    longitude: 88.5123,
    sensorType: 'Soil Moisture',
    soilMoisture: 89.4,
    currentValue: 89.4,
    unit: '%',
    threshold: 80.0,
    battery: 88,
    signalStrength: 92,
    lastUpdated: new Date().toISOString(),
    status: 'CRITICAL',
    trend: 'CRITICAL_SURGE',
    installationDepthM: 2.5,
    history: generateInitialHistory(89.4, 88, 92)
  },
  {
    sensorId: 'SEN-SK-TL-02',
    district: 'Pakyong',
    state: 'Sikkim',
    location: 'Singtam Cliff Face Borehole Inclinometer',
    latitude: 27.2360,
    longitude: 88.5140,
    sensorType: 'Slope Tilt',
    soilMoisture: 88.0,
    currentValue: 4.8,
    unit: '°',
    threshold: 3.5,
    battery: 91,
    signalStrength: 85,
    lastUpdated: new Date().toISOString(),
    status: 'CRITICAL',
    trend: 'RISING',
    installationDepthM: 8.0,
    history: generateInitialHistory(4.8, 91, 85)
  },
  {
    sensorId: 'SEN-SK-RG-03',
    district: 'Pakyong',
    state: 'Sikkim',
    location: 'Rangpo Checkpost Hydro-Met Automated Rain Gauge',
    latitude: 27.2105,
    longitude: 88.5020,
    sensorType: 'Rain Gauge',
    soilMoisture: 82.0,
    currentValue: 16.4,
    unit: 'mm/hr',
    threshold: 15.0,
    battery: 95,
    signalStrength: 96,
    lastUpdated: new Date().toISOString(),
    status: 'WARNING',
    trend: 'RISING',
    history: generateInitialHistory(16.4, 95, 96)
  },
  {
    sensorId: 'SEN-SK-GM-04',
    district: 'Pakyong',
    state: 'Sikkim',
    location: 'NH-10 Km 28 Tension Crack Wire Extensometer',
    latitude: 27.2280,
    longitude: 88.5080,
    sensorType: 'Ground Movement',
    soilMoisture: 86.5,
    currentValue: 14.2,
    unit: 'mm',
    threshold: 10.0,
    battery: 84,
    signalStrength: 80,
    lastUpdated: new Date().toISOString(),
    status: 'CRITICAL',
    trend: 'CRITICAL_SURGE',
    installationDepthM: 1.0,
    history: generateInitialHistory(14.2, 84, 80)
  },

  // 2. Meghalaya - East Khasi Hills (Cherrapunji Sohra Escarpment)
  {
    sensorId: 'SEN-ML-SM-01',
    district: 'East Khasi Hills',
    state: 'Meghalaya',
    location: 'Sohra Escarpment Sandstone Soil Profile',
    latitude: 25.2702,
    longitude: 91.7323,
    sensorType: 'Soil Moisture',
    soilMoisture: 92.5,
    currentValue: 92.5,
    unit: '%',
    threshold: 82.0,
    battery: 94,
    signalStrength: 90,
    lastUpdated: new Date().toISOString(),
    status: 'CRITICAL',
    trend: 'CRITICAL_SURGE',
    installationDepthM: 3.0,
    history: generateInitialHistory(92.5, 94, 90)
  },
  {
    sensorId: 'SEN-ML-RG-02',
    district: 'East Khasi Hills',
    state: 'Meghalaya',
    location: 'Cherrapunji AWS Tipping Bucket Gauge',
    latitude: 25.2750,
    longitude: 91.7380,
    sensorType: 'Rain Gauge',
    soilMoisture: 91.0,
    currentValue: 28.5,
    unit: 'mm/hr',
    threshold: 20.0,
    battery: 98,
    signalStrength: 94,
    lastUpdated: new Date().toISOString(),
    status: 'CRITICAL',
    trend: 'CRITICAL_SURGE',
    history: generateInitialHistory(28.5, 98, 94)
  },
  {
    sensorId: 'SEN-ML-TL-03',
    district: 'East Khasi Hills',
    state: 'Meghalaya',
    location: 'Shella Road Escarpment Bi-axial Tiltmeter',
    latitude: 25.2610,
    longitude: 91.7210,
    sensorType: 'Slope Tilt',
    soilMoisture: 87.0,
    currentValue: 3.2,
    unit: '°',
    threshold: 3.0,
    battery: 89,
    signalStrength: 82,
    lastUpdated: new Date().toISOString(),
    status: 'WARNING',
    trend: 'RISING',
    installationDepthM: 6.0,
    history: generateInitialHistory(3.2, 89, 82)
  },

  // 3. Manipur - Noney (Tupul Railway Corridor)
  {
    sensorId: 'SEN-MN-GM-01',
    district: 'Noney',
    state: 'Manipur',
    location: 'Tupul Tunnel 12 Portal Joint Extensometer',
    latitude: 24.7890,
    longitude: 93.6540,
    sensorType: 'Ground Movement',
    soilMoisture: 94.0,
    currentValue: 18.6,
    unit: 'mm',
    threshold: 12.0,
    battery: 79,
    signalStrength: 76,
    lastUpdated: new Date().toISOString(),
    status: 'CRITICAL',
    trend: 'CRITICAL_SURGE',
    installationDepthM: 1.5,
    history: generateInitialHistory(18.6, 79, 76)
  },
  {
    sensorId: 'SEN-MN-TL-02',
    district: 'Noney',
    state: 'Manipur',
    location: 'Ijei River Pier Foundation Tiltmeter',
    latitude: 24.7920,
    longitude: 93.6590,
    sensorType: 'Slope Tilt',
    soilMoisture: 93.0,
    currentValue: 5.1,
    unit: '°',
    threshold: 3.5,
    battery: 86,
    signalStrength: 88,
    lastUpdated: new Date().toISOString(),
    status: 'CRITICAL',
    trend: 'RISING',
    installationDepthM: 12.0,
    history: generateInitialHistory(5.1, 86, 88)
  },

  // 4. Assam - Dima Hasao (Haflong Hill Railway)
  {
    sensorId: 'SEN-AS-SM-01',
    district: 'Dima Hasao',
    state: 'Assam',
    location: 'Haflong Jatinga Valley Hill Cut Moisture Probe',
    latitude: 25.1764,
    longitude: 93.0234,
    sensorType: 'Soil Moisture',
    soilMoisture: 82.5,
    currentValue: 82.5,
    unit: '%',
    threshold: 80.0,
    battery: 92,
    signalStrength: 87,
    lastUpdated: new Date().toISOString(),
    status: 'WARNING',
    trend: 'RISING',
    installationDepthM: 2.0,
    history: generateInitialHistory(82.5, 92, 87)
  },
  {
    sensorId: 'SEN-AS-TL-02',
    district: 'Dima Hasao',
    state: 'Assam',
    location: 'Lumding-Badarpur Railway Cutting Inclinometer',
    latitude: 25.1820,
    longitude: 93.0180,
    sensorType: 'Slope Tilt',
    soilMoisture: 80.0,
    currentValue: 2.4,
    unit: '°',
    threshold: 3.0,
    battery: 88,
    signalStrength: 91,
    lastUpdated: new Date().toISOString(),
    status: 'ONLINE',
    trend: 'STABLE',
    installationDepthM: 5.0,
    history: generateInitialHistory(2.4, 88, 91)
  },

  // 5. Arunachal Pradesh - West Kameng (Bhalukpong Sela Axis)
  {
    sensorId: 'SEN-AR-TL-01',
    district: 'West Kameng',
    state: 'Arunachal Pradesh',
    location: 'Bhalukpong Defense Road Escarpment Inclinometer',
    latitude: 27.0125,
    longitude: 92.6450,
    sensorType: 'Slope Tilt',
    soilMoisture: 86.0,
    currentValue: 3.8,
    unit: '°',
    threshold: 3.5,
    battery: 96,
    signalStrength: 78,
    lastUpdated: new Date().toISOString(),
    status: 'WARNING',
    trend: 'RISING',
    installationDepthM: 10.0,
    history: generateInitialHistory(3.8, 96, 78)
  },
  {
    sensorId: 'SEN-AR-RG-02',
    district: 'West Kameng',
    state: 'Arunachal Pradesh',
    location: 'Tenga Valley High-Altitude Rain Gauge',
    latitude: 27.0250,
    longitude: 92.6580,
    sensorType: 'Rain Gauge',
    soilMoisture: 84.0,
    currentValue: 12.0,
    unit: 'mm/hr',
    threshold: 15.0,
    battery: 93,
    signalStrength: 84,
    lastUpdated: new Date().toISOString(),
    status: 'ONLINE',
    trend: 'STABLE',
    history: generateInitialHistory(12.0, 93, 84)
  },

  // 6. Mizoram - Aizawl
  {
    sensorId: 'SEN-MZ-GM-01',
    district: 'Aizawl',
    state: 'Mizoram',
    location: 'Bawngkawn Urban Slope Retaining Crackmeter',
    latitude: 23.7420,
    longitude: 92.7230,
    sensorType: 'Ground Movement',
    soilMoisture: 77.0,
    currentValue: 6.8,
    unit: 'mm',
    threshold: 10.0,
    battery: 81,
    signalStrength: 95,
    lastUpdated: new Date().toISOString(),
    status: 'ONLINE',
    trend: 'STABLE',
    installationDepthM: 1.0,
    history: generateInitialHistory(6.8, 81, 95)
  },
  {
    sensorId: 'SEN-MZ-SM-02',
    district: 'Aizawl',
    state: 'Mizoram',
    location: 'Ramhlun North Slope Moisture Node',
    latitude: 23.7510,
    longitude: 92.7310,
    sensorType: 'Soil Moisture',
    soilMoisture: 77.0,
    currentValue: 77.0,
    unit: '%',
    threshold: 80.0,
    battery: 87,
    signalStrength: 92,
    lastUpdated: new Date().toISOString(),
    status: 'ONLINE',
    trend: 'STABLE',
    installationDepthM: 2.0,
    history: generateInitialHistory(77.0, 87, 92)
  },

  // 7. Nagaland - Kohima
  {
    sensorId: 'SEN-NL-TL-01',
    district: 'Kohima',
    state: 'Nagaland',
    location: 'Phesama NH-29 Sinking Zone Multi-Point Inclinometer',
    latitude: 25.6420,
    longitude: 94.1120,
    sensorType: 'Slope Tilt',
    soilMoisture: 74.0,
    currentValue: 3.4,
    unit: '°',
    threshold: 3.0,
    battery: 85,
    signalStrength: 89,
    lastUpdated: new Date().toISOString(),
    status: 'WARNING',
    trend: 'RISING',
    installationDepthM: 7.5,
    history: generateInitialHistory(3.4, 85, 89)
  },
  {
    sensorId: 'SEN-NL-GM-02',
    district: 'Kohima',
    state: 'Nagaland',
    location: 'Dzülake Road Shoulder Extensometer',
    latitude: 25.6510,
    longitude: 94.1200,
    sensorType: 'Ground Movement',
    soilMoisture: 72.0,
    currentValue: 4.2,
    unit: 'mm',
    threshold: 10.0,
    battery: 90,
    signalStrength: 86,
    lastUpdated: new Date().toISOString(),
    status: 'ONLINE',
    trend: 'STABLE',
    installationDepthM: 1.2,
    history: generateInitialHistory(4.2, 90, 86)
  },

  // 8. Tripura - North Tripura
  {
    sensorId: 'SEN-TR-SM-01',
    district: 'North Tripura',
    state: 'Tripura',
    location: 'Jampui Hills Vanghmun Soil Profile Node',
    latitude: 23.9540,
    longitude: 92.2780,
    sensorType: 'Soil Moisture',
    soilMoisture: 38.0,
    currentValue: 38.0,
    unit: '%',
    threshold: 75.0,
    battery: 97,
    signalStrength: 98,
    lastUpdated: new Date().toISOString(),
    status: 'ONLINE',
    trend: 'STABLE',
    installationDepthM: 2.0,
    history: generateInitialHistory(38.0, 97, 98)
  },
  {
    sensorId: 'SEN-TR-RG-02',
    district: 'North Tripura',
    state: 'Tripura',
    location: 'Jampui Ridge Rain Gauge (Maintenance Node)',
    latitude: 23.9610,
    longitude: 92.2850,
    sensorType: 'Rain Gauge',
    soilMoisture: 36.0,
    currentValue: 0.0,
    unit: 'mm/hr',
    threshold: 15.0,
    battery: 12,
    signalStrength: 15,
    lastUpdated: '2026-09-04T18:00:00Z',
    status: 'OFFLINE',
    trend: 'STABLE',
    history: generateInitialHistory(0.0, 12, 15)
  }
];
